name: CI/CD Pipeline (DISABLED)

on:
  # Disabled for now - focus on manual deployment
  # push:
  #   branches: [ main, develop ]
  # pull_request:
  #   branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests & Lint
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
    
    # - name: Run backend linting
    #   run: |
    #     cd backend
    #     npm run lint || echo "Linting failed but continuing..."
    #   continue-on-error: true
    
    - name: Run backend tests
      run: |
        cd backend
        npm test
    
    - name: Build backend
      run: |
        cd backend
        npm run build

  frontend-tests:
    name: Frontend Tests & Build
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        rm -f package-lock.json
        npm install --legacy-peer-deps
    
    # - name: Run frontend linting
    #   run: |
    #     cd frontend
    #     npm run lint || echo "Linting failed but continuing..."
    #   continue-on-error: true
    
    - name: Run frontend tests
      run: |
        cd frontend
        npm test -- --coverage --watchAll=false --passWithNoTests
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build

  security-scan:
    name: Security Audit
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Backend security audit
      run: |
        cd backend
        npm install
        npm audit --audit-level=high
      continue-on-error: true
    
    - name: Frontend security audit
      run: |
        cd frontend
        npm install --legacy-peer-deps
        npm audit --audit-level=high
      continue-on-error: true