name: Deploy to Production

on:
  push:
    branches: [ main ]

jobs:
  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd backend
        npm install
    
    - name: Build backend
      run: |
        cd backend
        npm run build
    
    - name: Deploy to Render
      run: |
        echo "Backend build successful - ready for Render deployment"
        echo "Visit https://render.com to deploy this repository"

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install frontend dependencies
      run: |
        cd frontend
        rm -f package-lock.json
        npm install --legacy-peer-deps
    
    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        REACT_APP_API_URL: https://your-backend-url.onrender.com
    
    - name: Deploy to Vercel
      run: |
        echo "Frontend build successful - ready for Vercel deployment"
        echo "Visit https://vercel.com to deploy this repository"